export interface SkillGroup {
  title: string;
  items: string[];
}

export const skillGroups: SkillGroup[] = [
  {
    title: "Frontend",
    items: ["React", "TypeScript", "Tailwind CSS", "Vite"],
  },
  {
    title: "Animation",
    items: ["Motion", "GSAP", "Scroll-driven UI"],
  },
  {
    title: "Creative",
    items: ["Canvas 2D", "WebGL / GLSL", "MediaPipe", "Web Audio API"],
  },
  {
    title: "Backend",
    items: ["Node.js", "FastAPI", "PostgreSQL", "MongoDB"],
  },
  {
    title: "Tools",
    items: ["Git", "GitHub", "Docker", "Figma"],
  },
];

export interface Capability {
  index: string;
  title: string;
  description: string;
  tags: string[];
}

export const capabilities: Capability[] = [
  {
    index: "01",
    title: "Front-end Development",
    description:
      "Production interfaces with strict TypeScript, component systems that scale, and performance budgets taken seriously.",
    tags: ["React", "TypeScript", "Tailwind"],
  },
  {
    index: "02",
    title: "Creative Development",
    description:
      "Canvas, WebGL and shader work — visuals generated by code, not assets.",
    tags: ["WebGL", "GLSL", "Canvas"],
  },
  {
    index: "03",
    title: "Interactive UI",
    description:
      "Interfaces that respond: gesture input, drag physics, state machines for complex interaction.",
    tags: ["MediaPipe", "Pointer Events", "State Machines"],
  },
  {
    index: "04",
    title: "Web Animation",
    description:
      "Motion with intent — scroll choreography, transitions and micro-interactions that explain rather than decorate.",
    tags: ["Motion", "GSAP", "Lenis"],
  },
  {
    index: "05",
    title: "Back-end Development",
    description:
      "APIs and data models behind the interface — typed, tested and boring in the best way.",
    tags: ["Node.js", "FastAPI", "SQL"],
  },
  {
    index: "06",
    title: "Experimental Web",
    description:
      "Small proofs of concept that answer 'what if' — audio, vision, generative systems.",
    tags: ["Web Audio", "Computer Vision", "Generative"],
  },
];
